import type { NextPage } from 'next'
import Head from 'next/head'
import AboutScreen from './Screens/AboutScreen'
import HomeScreen from './Screens/HomeScreen'

const Home: NextPage = () => {


  return (
    <div className='relative bg-black-prime'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HomeScreen /> */}

      <AboutScreen />

    </div>
  )
}

export default Home
